### ISSUE TITLE
Copy pasted code without credit or licensing

### ISSUE THREAD

**Issue by sinai-dev** [Fukashiro-Yukari/LuaLoader#2]
Hey, I'm flattered you thought my code was good enough to paste, but please give credit and follow proper licensing.

UnityExplorer is GPL3, meaning you must provide credit for code you used and also use an open source license for your project. Thanks!

<s>edit: oh and if that is Denikson's mcs-unity you're using you might want to credit him too.</s> nvm

**Comment by Fukashiro-Yukari** [comment]
Ok, i done

**Comment by sinai-dev** [comment]
Much appreciated! Good luck with your project, it looks great 👍
